# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 070ab167a0f49fead2dda806e84a48cf62a2000b3009278acb01995600274d7ee0456a328cc273144e6ecef3dec31467f759e6e28af29b9502b2dc15cdaab1b4

test:
  secret_key_base: a21b7006c0e2149ab98bcd25d3739ebfaee980584e2b3e2af38c914b64151dae42942d364fc451eb5b55db3629e48c85b886173ea87ace740322e393b3649561

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
